language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install python-numpy python-nose python-imaging python-scipy python-pygame
  - sudo bash SimpleCV/scripts/install/ubuntu/opencv_2_4_5.sh

install: "pip install -r requirements.txt --use-mirrors"

virtualenv:
  system_site_packages: true

script:
- cd SimpleCV/tests/
- nosetests -v tests.py
